### ISSUE TITLE
Good to.. TODO

### ISSUE THREAD

**Issue by Mitri45** [Mitri45/bmi-calculator#1]
- [ ] Add responsive design with media queries
- [ ] Add modal dialog when user click delete records button
- [ ] Add hovers to chart points with BMI results
- [ ] Add colors to chart point according to results
